Implement cinema mode
OpenSlides/OpenSlides pull request #5515
Opened 2020-08-19 13:10 UTC by tsiegleauq

Implements a viewer mode containing the most important information and
Heavily refactors ListOfSpeaker and CurrentListOfSpeaker
interaction heavy components on a single view:

Current List of Speakers
Currently Open Polls
Current projector

2020-09-04 13:06 UTC, emanuelschuetze requested changes
please rename url "cinema" in "autopilot"

2020-09-04 13:37 UTC, tsiegleauq commented
> please rename url "cinema" in "autopilot"

done

2020-09-17 15:33 UTC, emanuelschuetze commented
Please rebase and adapt migration.

2020-09-23 06:36 UTC, emanuelschuetze approved these changes

2020-09-23 06:37 UTC, merged