Fix non-multipl os-search-val-selector
OpenSlides/OpenSlides pull request #5690
Opened 2020-11-09 14:36 UTC by tsiegleauq

Fixes a bug there non multiple uses of search value
selector was submitting the value twice due to late
alterations of internal form objects

fixes #5688

2020-11-09 20:36 UTC, emanuelschuetze requested changes
Try to add a speaker to a list of speakers. I get this TypeError in console:

```
ERROR TypeError: this.contentForm.value.includes is not a function
    at search-value-selector.component.ts:128
```

Same error if you open the motion create form. You cannot save a new motion!

2020-11-09 20:37 UTC, emanuelschuetze commented
Please check also #5689!

2020-11-10 10:15 UTC, tsiegleauq commented
fixed. #5689 is irrelevant for that bug

2020-11-11 19:54 UTC, emanuelschuetze approved these changes

2020-11-11 19:54 UTC, merged