Show "please grant mic access" info
OpenSlides/OpenSlides pull request #5695
Opened 2020-11-10 14:30 UTC by tsiegleauq

If the browser does not have the permission to use the microphone,
OpenSlides will show a spinner to inform the user to grant
mic access

2020-11-10 14:32 UTC, tsiegleauq commented
![image](https://user-images.githubusercontent.com/10233032/98687338-e9718000-2369-11eb-980c-1e5e566a6f3f.png)

2020-11-11 07:32 UTC, emanuelschuetze requested changes
Does NOT work in Firefox! Try to open Jitsi gets this error message in OpenSlides:
`'microphone' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.`

Chromium works for me as expected.

2020-11-16 12:37 UTC, tsiegleauq commented on client/src/app/core/ui-services/user-media-perm.service.ts
> +     */
@emanuelschuetze to prevent questions why this behaves the way it dies, understanding this is important.

2020-11-24 10:49 UTC, emanuelschuetze requested changes
As discussed:
- please combine mic/camera permission to _one_ permission request (while connecting); adjust spinner message
- add 2 new config options to set default mic and camera to active/inactive

2020-11-26 09:38 UTC, jsangmeister commented
Fixed config usage. Works now.

2020-11-26 11:06 UTC, emanuelschuetze approved these changes

2020-11-26 11:06 UTC, merged