Autoconnect the next X speaker to jitsi
OpenSlides/OpenSlides pull request #5707
Opened 2020-11-18 11:33 UTC by tsiegleauq

In config, set "general_system_conference_auto_connect_next_speakers"
to let the next X speakers on the current list of speakers
automatically join the jitsi conference.
Updates automatically

2020-11-19 07:31 UTC, FinnStutzenstein commented on client/src/app/site/agenda/models/view-list-of-speakers.ts
> +    public findUserIndexOnList(userId: number): number {
You can use `UserListIndexType` as the return type.

2020-11-19 07:34 UTC, FinnStutzenstein approved these changes
Code looks good

2020-11-24 10:45 UTC, emanuelschuetze requested changes
Please don't autoconnect if user was started with "play" button on list of speaker.

Use case:
User A is on position 1 in the LOS. Finished his speach. Exit jitsi. Admin has forgot to click play and stop. Do it now. Now: User A autoconnects again to jitsi! - > Please prevent this!

Only the x users on the next speakers list should autoconnect to jitsi. Current speaker should do nothing.

2020-11-25 13:29 UTC, emanuelschuetze approved these changes

2020-11-25 14:05 UTC, emanuelschuetze commented
fixed typo and config order. rebased.

2020-11-25 14:29 UTC, merged