Fix csv importing users with groups
OpenSlides/OpenSlides pull request #5823
Opened 2021-01-25 17:27 UTC by tsiegleauq

old groups
new groups created on the fly

2021-01-25 20:19 UTC, emanuelschuetze requested changes
Can't import a csv files with new groups!
Example:
Open demo csv file. Change a default group into a new group (e.g. "foo"). Now try to import this file: Preview looks good. "foo" should be created. After clicking "Import" the new group is created successfully but the user was not imported ("failure - 0 imported"). Same error after reimport the same file...

2021-01-26 06:25 UTC, FinnStutzenstein commented on client/src/app/site/users/components/user-import/user-import-list.component.html
> +                <span *ngFor="let group of groups; let i = index">
You can use `...;let last = last">` and than `<span *ngIf="!last">
(https://angular.io/api/common/NgForOf#local-variables)

2021-01-26 10:06 UTC, emanuelschuetze approved these changes

2021-02-04 14:59 UTC, emanuelschuetze approved these changes

2021-02-04 20:51 UTC, emanuelschuetze commented
@FinnStutzenstein: @tsiegleauq needs your short review please

2021-02-05 08:29 UTC, FinnStutzenstein approved these changes

2021-02-05 09:38 UTC, merged