unique version tag for docker images
OpenSlides/OpenSlides pull request #6224
Opened 2021-09-14 15:14 UTC by peb-adr

will generated an image tag of the form `VERSION-YYYYMMDD-GITHUB_SHA` e.g. `4.0-dev-20210914-deadbeef` whenever an image is built by github actions.
The new image will also be tagged and pushed as `latest`. So the compose template in the manage-service should be changed to pull the `latest` images in order to continue to work as expected.

Additionally the generated version string will be put into `openslides-client/version.txt` so that it can be used/displayed in the client.

2021-09-21 20:20 UTC, normanjaeckel requested changes
Two small changes, rest is ok. After merge please remove old images from GitHub Container Registry

2021-09-21 20:20 UTC, normanjaeckel commented on .github/workflows/build_images.yml
> +  IMAGE_VERSION: 4.0-dev
Please change this back to 4.0.0-dev to get a correct semver version (https://semver.org)

2021-09-21 20:20 UTC, normanjaeckel commented on .github/workflows/build_images.yml
> +  TAG_SUFFIX: -$(date +%Y%m%d)-${GITHUB_SHA::7}
Please change to -$(date +%Y-%m-%d)-${GITHUB_SHA::7} to get a ISO compliant date format.

2021-09-23 08:49 UTC, peb-adr commented
@normanjaeckel @emanuelschuetze done

2021-09-23 12:41 UTC, emanuelschuetze approved these changes

2021-09-23 15:21 UTC, peb-adr commented on .github/workflows/build_images.yml
> +  TAG_SUFFIX: -$(date +%Y-%m-%d)-${GITHUB_SHA::7}
I honestly prefer `4.0.0-dev-20210923-1234567` as well.
@normanjaeckel requested an iso compliant date with dashes. But it looks clearer without them imo

2021-09-23 16:05 UTC, normanjaeckel commented
Looks like that the basic format YYYYMMDD is also valid, see https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates

So it is ok for me here.

2021-09-23 16:06 UTC, normanjaeckel commented on .github/workflows/build_images.yml
> +  TAG_SUFFIX: -$(date +%Y-%m-%d)-${GITHUB_SHA::7}
Looks like that the basic format YYYYMMDD is also valid, see https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates

So it is ok for me here.

2021-09-23 16:07 UTC, normanjaeckel approved these changes

2021-09-23 16:57 UTC, peb-adr commented on .github/workflows/build_images.yml
> +            eval echo ${IMAGE_VERSION}${TAG_SUFFIX} > version.txt
done

2021-09-23 16:57 UTC, peb-adr commented on .github/workflows/build_images.yml
> +  TAG_SUFFIX: -$(date +%Y-%m-%d)-${GITHUB_SHA::7}
and done

2021-09-24 08:36 UTC, merged