Updated README.md and added INSTALL.md
OpenSlides/OpenSlides pull request #6522
Opened 2022-12-08 21:03 UTC by normanjaeckel

2022-12-09 07:59 UTC, rrenkert commented on INSTALL.md
> +Compose](https://docs.docker.com/compose/) installed and the Docker daemon is
Do we have a minimum docker/compose version?

2022-12-09 07:59 UTC, rrenkert commented on INSTALL.md
> +### Reach OpenSlides from outside your local machin
Typo: Missing "e" in machin"e"

2022-12-09 07:59 UTC, rrenkert commented on INSTALL.md
> +
To do a deeper cleanup (networks and containers) there is 
    $ docker-compose down

I think we should add this here.

2022-12-09 07:59 UTC, rrenkert commented on INSTALL.md
> +much more. To rebuild the Docker Compose YAML file without resetting the whole
Do we have a more detailed description of "much more"?

2022-12-12 08:44 UTC, jsangmeister requested changes

2022-12-13 20:01 UTC, emanuelschuetze commented on README.md
> +mentioned in the [AUTHORS file](AUTHORS).
Done in #6524

2022-12-13 20:23 UTC, merged