Document update process + env var changes
OpenSlides/OpenSlides pull request #6624
Opened 2023-07-20 18:56 UTC by peb-adr

2023-07-20 18:56 UTC, peb-adr commented
relevant issue: https://github.com/OpenSlides/openslides-manage-service/issues/224

2023-07-21 07:51 UTC, jsangmeister requested changes
Some nitpicking :)

2023-07-21 07:51 UTC, jsangmeister commented on INSTALL.md
> +The docker images of Every OpenSlides stable update are tagged as `latest`.
```suggestion
The docker images of every OpenSlides stable update are tagged as `latest`.
```

2023-07-21 07:51 UTC, jsangmeister commented on INSTALL.md
> +So for many updates pulling the new ones and re-running `up` as described [above](#Pull images and start services).
```suggestion
So for most updates pulling the new ones and re-running `up` as described [above](#Pull images and start services) suffices.
```

2023-07-21 07:51 UTC, jsangmeister commented on INSTALL.md
> +However this can be unreliable if `docker` fails to recognize a new image in the registry.
```suggestion
However, this can be unreliable if `docker` fails to recognize a new image in the registry.
```

2023-07-21 07:51 UTC, jsangmeister commented on INSTALL.md
> +On the other hand it can mean services will update "by themselves" due to silently using a new image.
```suggestion
On the other hand, it can mean services will update "by themselves" due to silently using a new image.
```

2023-07-21 07:51 UTC, jsangmeister commented on INSTALL.md
> +It is therefore recommended to pin the version explicitly in the `config.yml` like so
```suggestion
It is therefore recommended to pin the version explicitly in the `config.yml` like this:
```

2023-07-21 07:51 UTC, jsangmeister commented on INSTALL.md
> +To update to the new version set the new tag and regenerate the compose file and
```suggestion
To update to the new version, set the new tag, regenerate the compose file and
```

2023-07-21 07:51 UTC, jsangmeister commented on INSTALL.md
> +Some updates include migrations that must be ran on the database.
```suggestion
Some updates include migrations that must be run on the database.
```

2023-07-21 07:51 UTC, jsangmeister commented on INSTALL.md
> +To check the current status and start migrations if necessary run
```suggestion
To check the current status and start migrations if necessary, run:
```

2023-07-21 07:51 UTC, jsangmeister commented on INSTALL.md
> +    `DATABASE_*`. So if custom values were used this must be reflected in config
```suggestion
    `DATABASE_*`. If custom values were used, this must be reflected in config
```

2023-07-24 15:32 UTC, merged